services:
  db:
    container_name: oderco-warehouse-db
    image: mysql:latest
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
# Recomendável abrir a porta, pois os testes dependem que o banco de dados
# esteja online e acessível
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 10
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: oderco-warehouse-server
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: local
      APP_KEY: base64:4JFY6GLzEcpmULIrp/5B+gVQOgSg6JmkkeSEjwUDNKA=
      APP_NAME: Oderco Warehouse
      DB_CONNECTION: mysql 
      DB_HOST: oderco-warehouse-db
      DB_PORT: 3306
      DB_DATABASE: oderco
      DB_USERNAME: root
      DB_PASSWORD: root
      FILESYSTEM_DISK: public
      ASSET_URL: http://localhost:3000
    volumes:
      - server-static:/var/www/public
      - storage:/var/www/storage/app/public
      - ./server/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  nginx-server:
    image: nginx:alpine
    container_name: nginx-server
    volumes:
      - ./nginx-server/conf.d:/etc/nginx/conf.d
      - server-static:/var/www/public
      - storage:/var/www/storage/app/public
    depends_on:
      - server
  web:
    build:
      context: ./web
      dockerfile: Dockerfile 
    depends_on:
      - nginx-server
    environment:
      NUXT_SERVER_URL: http://nginx-server
    ports:
      - 3000:3000
volumes:
  server-static:
  storage:
